### ISSUE TITLE
Leyenda

### ISSUE THREAD

**Issue by isapozuelo** [GeographicaGS/waze-www#24]
//Leyenda - Zoom inicial coropletas//

-- ES
Nivel de impacto en los distritos
- Leve
- Moderado
- Grave

-- EN
Impact level in districts
- Low
- Moderate
- Severe

**Comment by isapozuelo** [comment]
// Leyenda - Traffic jams level//

-- ES
Niveles de atascos
- Leve
- Moderado
- Grave - tráfico intenso
- Severo - retenciones

-- EN
Traffic jam levels
- Light
- Moderate
- Heavy - intense traffic
- Standstill - blocked

**Comment by alasarr** [comment]
@javigil-geo está trabajando en la leyenda

**Comment by isapozuelo** [comment]
// Niveles de servicio//

-- ES
Niveles de servicio
- Fluido
- Lento
- Retenciones
- Congestión
- Cortado
- Sin datos

-- EN
Level of service
- Fluid
- Slow
- Road delays
- Standstill
- Closed
- No data
