### ISSUE TITLE
Traducciones

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/waze-www#30]
Todo en español

**Comment by isapozuelo** [comment]
@padawannn aquí tienes, le he puesto la extensión txt al archivo para que me dejara subirlo.

[en.json.txt](https://github.com/GeographicaGS/waze-www/files/1457476/en.json.txt)

**Comment by isapozuelo** [comment]
Traducción de subtipos @padawannn 
[subtype.txt](https://github.com/GeographicaGS/waze-www/files/1458602/subtype.txt)
